## Linear Regression with Pytorch

In [1]:
import torch
from torch import nn


class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1,requires_grad=True, dtype = torch.float))
        self.bias = nn.Parameter(torch.randn(1,requires_grad=True, dtype = torch.float))
        
    # Forward method to define the computation method in the model
    def forward(self, feature: torch.Tensor) -> torch.Tensor: # feature: is the input data
        return self.weights * feature + self.bias
        
        

In [4]:
# Instantiate a model
model_fn = LinearRegression()
model_fn.weights , model_fn.bias

(Parameter containing:
 tensor([-1.0707], requires_grad=True),
 Parameter containing:
 tensor([1.1926], requires_grad=True))

In [7]:
# Dummy dataset 
X = torch.range(start=0, end=1, step=0.02).unsqueeze(dim = 1)
y = 0.7 * X + 0.3  
print(f"Features: {X}")
print(f"Targets: {y}")

Features: tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800],
        [1.0000]])
Targets: tensor([[0.3000],
        [0.3140],
        [0.3280],
        

/var/folders/4d/rdp7yqvj08d6bhjwt9ryxkth0000gn/T/ipykernel_3390/3249183443.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  X = torch.range(start=0, end=1, step=0.02).unsqueeze(dim = 1)


In [8]:
with torch.inference_mode():
    y_preds = model_fn(X)
    
y_preds

tensor([[1.1926],
        [1.1712],
        [1.1498],
        [1.1284],
        [1.1069],
        [1.0855],
        [1.0641],
        [1.0427],
        [1.0213],
        [0.9999],
        [0.9785],
        [0.9570],
        [0.9356],
        [0.9142],
        [0.8928],
        [0.8714],
        [0.8500],
        [0.8286],
        [0.8072],
        [0.7857],
        [0.7643],
        [0.7429],
        [0.7215],
        [0.7001],
        [0.6787],
        [0.6573],
        [0.6358],
        [0.6144],
        [0.5930],
        [0.5716],
        [0.5502],
        [0.5288],
        [0.5074],
        [0.4859],
        [0.4645],
        [0.4431],
        [0.4217],
        [0.4003],
        [0.3789],
        [0.3575],
        [0.3360],
        [0.3146],
        [0.2932],
        [0.2718],
        [0.2504],
        [0.2290],
        [0.2076],
        [0.1862],
        [0.1647],
        [0.1433],
        [0.1219]])