In [1]:
import torch
torch.manual_seed(0)

In [2]:
example = torch.rand(5,3)


In [3]:
available_device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Device: {available_device}")

Device: mps


In [4]:
device = torch.device(available_device)

In [5]:
x = torch.randn(5,3, requires_grad=True)
y = x + 2
print(y)

tensor([[2.6035, 2.8110, 1.9549],
        [2.8797, 3.0482, 1.9555],
        [1.2771, 4.8663, 1.4345],
        [2.1604, 1.9746, 3.0739],
        [4.2628, 1.0825, 1.7749]], grad_fn=<AddBackward0>)


In [11]:
# Slicing example
example = torch.rand(3,3, requires_grad=True).to(device)
print(example)
print(example[:2, :])

tensor([[0.0012, 0.5936, 0.4158],
        [0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529]], device='mps:0', grad_fn=<ToCopyBackward0>)
tensor([[0.0012, 0.5936, 0.4158],
        [0.4177, 0.2711, 0.6923]], device='mps:0', grad_fn=<SliceBackward0>)


In [12]:
example.get_device()

0

In [13]:
# Preventing gradient history
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    
    
    
    

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
